const GOOGLE_SCRIPT_URL = "https://script.google.com/macros/s/AKfycby0wRyLs7tQFpiP0x3N_K_2zVvPAMPWACBaazToSQt6iVZtIY2dk0xm7vsTmJGXPcPRtg/exec";

// IMPORTANT: Jo Hugging Face ka Direct URL aapne copy kiya hai, use yahan paste karein (bina aakhiri slash '/' ke)
const HUGGING_FACE_API_URL = "https://pvc-cropper-api-pvc-cropper-api.hf.space";

let currentUser = "";

// 1. LOGIN LOGIC
async function loginUser() {
    const userInp = document.getElementById("username").value;
    const passInp = document.getElementById("password").value;
    const errorTxt = document.getElementById("login-error");

    if(!userInp || !passInp) return alert("Please fill all fields");

    try {
        currentUser = userInp;
        document.getElementById("login-box").classList.add("hidden");
        document.getElementById("dashboard").classList.remove("hidden");
        document.getElementById("user-display").innerText = currentUser;
        document.getElementById("wallet-balance").innerText = "50"; 
        
        fetch(GOOGLE_SCRIPT_URL, {
            method: "POST",
            mode: "no-cors",
            body: JSON.stringify({ action: "login", userId: userInp, password: passInp })
        });
    } catch (err) {
        errorTxt.innerText = "Server Error. Try Again!";
        errorTxt.classList.remove("hidden");
    }
}

// 2. FILE UPLOAD HANDLER
function handleFileUpload() {
    const fileInput = document.getElementById("document-file");
    const statusTxt = document.getElementById("upload-status");
    const btn = document.getElementById("process-btn");

    if(fileInput.files.length > 0) {
        statusTxt.innerHTML = "<strong>Selected:</strong> " + fileInput.files[0].name;
        btn.classList.remove("hidden");
    }
}

// 3. MULTI-CARD PROCESSING WITH PYTHON INTEGRATION (FINAL)
async function processSelectedCard() {
    let currentBal = parseFloat(document.getElementById("wallet-balance").innerText);
    const cardType = document.getElementById("card-type").value;
    const pdfPassword = document.getElementById("pdf-password").value;
    const fileInput = document.getElementById("document-file");
    const btn = document.getElementById("process-btn");

    if(currentBal < 2) {
        return alert("Low Balance! Please recharge your wallet.");
    }
    if(fileInput.files.length === 0) {
        return alert("Please upload a file first!");
    }

    // Button loading state
    btn.innerText = "⏳ Processing... Please Wait...";
    btn.disabled = true;

    try {
        // Step A: Deduct ₹2 from Google Sheet Database
        await fetch(GOOGLE_SCRIPT_URL, {
            method: "POST",
            mode: "no-cors",
            body: JSON.stringify({ action: "deduct_balance", userId: currentUser })
        });

        currentBal -= 2;
        document.getElementById("wallet-balance").innerText = currentBal;

        // Step B: Send file to Hugging Face Python Engine
        const file = fileInput.files[0];
        
        // Gradio API standard format requires data array
        const formData = new FormData();
        formData.append("data", file); 
        // We will pass text inputs via query params or multi-part depending on Gradio version,
        // for standard zero-code endpoint wrapper, sending directly via Gradio API fetch:
        
        let reader = new FileReader();
        reader.readAsDataURL(file);
        reader.onload = async function () {
            const base64Data = reader.result;

            const response = await fetch(`${HUGGING_FACE_API_URL}/api/predict`, {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({
                    data: [
                        { "name": file.name, "data": base64Data },
                        cardType,
                        pdfPassword
                    ]
                })
            });

            const result = await response.json();
            
            if (result && result.data && result.data[0]) {
                // Download file generated by Python
                const fileUrl = `${HUGGING_FACE_API_URL}/file=${result.data[0].name}`;
                
                const downloadAnchor = document.createElement("a");
                downloadAnchor.href = fileUrl;
                downloadAnchor.download = `${cardType}_pvc_ready.png`;
                document.body.appendChild(downloadAnchor);
                downloadAnchor.click();
                document.body.removeChild(downloadAnchor);
                
                alert("✨ Premium PVC layout generated and downloaded successfully!");
            } else {
                alert("Processing failed on engine. Check file format or password.");
            }
            
            btn.innerText = "⚙️ Process Card & Deduct ₹2";
            btn.disabled = false;
        };

    } catch(e) {
        alert("Transaction or Engine connection failed!");
        btn.innerText = "⚙️ Process Card & Deduct ₹2";
        btn.disabled = false;
    }
}
